apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: kelvin666888/nodejs-app
  newName: kelvin666888/nodejs-app
  newTag: 2ebbd0bc7d170fea462effeaa438c88d07a4254c
