apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: kelvin666888/nodejs-app
  newName: kelvin666888/nodejs-app
  newTag: b958105f32bafc7afc43b44e048807da8fd33441
