apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: kelvin666888/nodejs-app
  newName: kelvin666888/nodejs-app
  newTag: 0c80e385d8a3d25c95cbe222e2c0b12a67d428fe
